test: &default

  # Credentials for REST APIs
  client_id: Aeg2dnWMf0Y795MhAlV4LKGJqxcxtxkr-1SoQK948dTqTSBZbCcDedu-dhwp6fmGz_x9FV1Rr_0Wmf9p
  client_secret: EL_t7UUzUv6zFMP-7ZQmhbQ-i6PmZKcqQHFun_Q2vtwLbaPc2UVdAXJgHUTIoClRZBnVIH4ojsTKkYRH

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: padre_gpaj@protonmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
